### ISSUE TITLE
0.2 pcb - User JTAG TCK not routed to clock capable pin

### ISSUE THREAD

**Issue by GregAC** [newaetech/sonata-pcb#5]
The USR_JTAG_TCK net is routed to pin H17 which is not a clock capable pin. Our JTAG TAP implementation uses TCK as a clock (i.e. in a `alway_ff @(posedge tck)` block). As TCK doesn't need to be fast and has little logic connected to it this may not be a problem (we could always refactor the TAP so it doesn't use TCK directly as a clock as well) however it would be preferable for it to be routed to a clock capable pin if possible.

**Comment by GregAC** [comment]
@colinoflynn please note

**Comment by colinoflynn** [comment]
Oops! Might be another pin-swap problem, will re-route it to a clock pin if reasonable. For now I'd just delegate it to a warning, with the small(ish) logic I probably wouldn't worry about that. I'll get @jpcrypt's input as well once he's available.

**Comment by GregAC** [comment]
I've got JTAG over FTDI working so I can load and debug programs on the Ibex demo system with a 10 MHz JTAG clock (or at least that's what OpenOCD claims...)

So a fix for this is in the nice to have bucket but certainly not essential. Could be it's not always reliable at 10 MHz, could try to do some stress testing to determine this. We can always lower the speed if needed.

**Comment by colinoflynn** [comment]
Pinswap:
![image](https://github.com/newaetech/sonata-pcb/assets/6100154/a00108c4-a372-4d8d-809c-4c7de0b75d0d)

**Comment by colinoflynn** [comment]
Now routed to a SRCC pin (assume SRCC is fine & not MRCC)

**Comment by colinoflynn** [comment]
Closed accidently with commit message, will leave open until we actually have new PCBs so can see at a glance issues on current protos.

**Comment by colinoflynn** [comment]
Issue is on 0.3 PCB (now on order) & will be tested once board is built. Issue will be closed once fix is confirmed.
