### ISSUE TITLE
0.2 pcb - LCD_BACKLIGHT pin doesn't go anywhere

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/sonata-pcb#9]
As reported by @GregAC - LCD_BACKLIGHT isn't routed to the FPGA (but does have a single resistor on it so didn't get an ERC when checking).

Easiest is just for the LCD on, by shorting between these pins:
![image](https://github.com/newaetech/sonata-pcb/assets/6100154/fbb6970f-07d7-4400-9b9c-0f79e6161f48)

The relevant schematic section:
![image](https://github.com/newaetech/sonata-pcb/assets/6100154/187423e9-7d14-4d94-8ba4-71bb84dadc35)

You can also run a bodge wire from the side of R133 that connects to the Q2 gate to an FPGA pin. But in practice the LCD shouldn't need backlight dimming, so just turning it ON is fine.

**Comment by GregAC** [comment]
![PXL_20240109_150148601 MP](https://github.com/newaetech/sonata-pcb/assets/471032/eded3990-f833-404c-beae-ec0534949c8c)

I just used a big blob of solder to bridge the connections, looks to be working well

![PXL_20240109_212340053](https://github.com/newaetech/sonata-pcb/assets/471032/4bf2894c-a056-49f6-bc92-aa16bcd23375)

**Comment by colinoflynn** [comment]
Issue is fixed on 0.3 PCB (now on order) & will be tested once board is built. Issue will be closed once fix is confirmed.
